In [1]:
import numpy as np

# Define groups and slots
groups = ['G1', 'G2', 'G3', 'G4']
slots = ['Mo07', 'Mo08', 'Tu07', 'Tu08']

def generate_random_weights(base_weights, num_variations=5):
    # Create multiple variations of the weights matrix
    variations = []
    for _ in range(num_variations):
        # Add random noise of order 2 to the base weights
        noise = np.random.uniform(-2, 2, base_weights.shape)
        # Ensure weights remain positive by taking absolute value
        new_weights = np.abs(base_weights + noise)
        variations.append(new_weights)
    return variations

# Base weights matrix
base_weights = np.array([
    [4, 2, 1, 3],  # G1's weights
    [1, 3, 4, 2],  # G2's weights
    [2, 4, 3, 1],  # G3's weights
    [3, 1, 2, 4]   # G4's weights
])

def gale_shapley_matching(weights):
    # Convert weights to preferences
    preferences = np.argsort(weights, axis=1)
    
    # Initialize all groups and slots as free
    free_groups = set(range(len(groups)))
    matches = [-1] * len(slots)
    group_proposals = [0] * len(groups)
    
    while free_groups:
        g = free_groups.pop()
        s = preferences[g][group_proposals[g]]
        group_proposals[g] += 1
        
        if matches[s] == -1:
            matches[s] = g
        else:
            current_g = matches[s]
            if weights[current_g][s] > weights[g][s]:
                matches[s] = g
                free_groups.add(current_g)
            else:
                free_groups.add(g)
    
    return matches

# Generate multiple variations of weights
weight_variations = generate_random_weights(base_weights, num_variations=5)

# Run the algorithm for unrandomized weights
print("Unrandomized scenario:\n")
print("Weights matrix:")
print(" ",*slots)
print(base_weights.round(2))
final_matches = gale_shapley_matching(base_weights)
print("\nMatching results:")
for slot_idx, group_idx in enumerate(final_matches):
    print(f"{slots[slot_idx]} -> {groups[group_idx]}")
print("\n" + "-"*40 + "\n")

# Run the algorithm for each variation
print("Randomized scenarios:\n")
for i, weights in enumerate(weight_variations, 1):
    print(f"Scenario {i}:")
    print("Weights matrix:")
    print(" ",*slots)
    print(weights.round(2))
    final_matches = gale_shapley_matching(weights)
    print("\nMatching results:")
    for slot_idx, group_idx in enumerate(final_matches):
        print(f"{slots[slot_idx]} -> {groups[group_idx]}")
    print("\n" + "-"*40 + "\n")

Unrandomized scenario:

Weights matrix:
  Mo07 Mo08 Tu07 Tu08
[[4 2 1 3]
 [1 3 4 2]
 [2 4 3 1]
 [3 1 2 4]]

Matching results:
Mo07 -> G2
Mo08 -> G4
Tu07 -> G1
Tu08 -> G3

----------------------------------------

Randomized scenarios:

Scenario 1:
Weights matrix:
  Mo07 Mo08 Tu07 Tu08
[[5.77 1.03 2.15 2.73]
 [1.81 3.34 2.86 0.22]
 [0.2  4.29 4.95 1.31]
 [3.55 2.84 2.64 2.75]]

Matching results:
Mo07 -> G3
Mo08 -> G1
Tu07 -> G4
Tu08 -> G2

----------------------------------------

Scenario 2:
Weights matrix:
  Mo07 Mo08 Tu07 Tu08
[[4.53 3.46 2.02 2.7 ]
 [1.56 2.7  4.6  3.9 ]
 [1.58 4.62 3.59 0.28]
 [1.67 1.4  3.64 4.5 ]]

Matching results:
Mo07 -> G2
Mo08 -> G4
Tu07 -> G1
Tu08 -> G3

----------------------------------------

Scenario 3:
Weights matrix:
  Mo07 Mo08 Tu07 Tu08
[[4.55 3.11 1.14 4.51]
 [0.64 4.8  2.61 0.62]
 [2.34 2.19 4.85 0.44]
 [2.6  0.23 3.86 3.63]]

Matching results:
Mo07 -> G2
Mo08 -> G4
Tu07 -> G1
Tu08 -> G3

----------------------------------------

Scenario 4:
Weigh

In [3]:
import numpy as np
import pandas as pd

def create_sample_data(num_groups):
    group_data_dict = {}
    time_slots = [f"{i:02d}:00" for i in range(7, 17)]
    days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
    for i in range(num_groups):
        data = {'Time': time_slots}
        for day in days:
            data[day] = np.random.rand(len(time_slots)) * 10
        group_data_dict[f'Group{i+1}'] = pd.DataFrame(data)
    return group_data_dict

# Define groups and slots
groups = [f'Group{i+1}' for i in range(4)]
slots = ['Mon_07:00', 'Mon_08:00', 'Tue_07:00', 'Tue_08:00']

def generate_random_weights(base_weights, num_variations=5):
    # Create multiple variations of the weights matrix
    variations = []
    for _ in range(num_variations):
        # Add random noise of order 2 to the base weights
        noise = np.random.uniform(-2, 2, base_weights.shape)
        # Ensure weights remain positive by taking absolute value
        new_weights = np.abs(base_weights + noise)
        variations.append(new_weights)
    return variations

# Base weights matrix - now derived from sample data
sample_data = create_sample_data(4)
print(sample_data)
base_weights = np.array([
    [sample_data[g].loc[
        sample_data[g].Time == s.split('_')[1],
        s.split('_')[0]
    ].values[0] for s in slots
    ] for g in groups
])

def gale_shapley_matching(weights):
    # Convert weights to preferences
    preferences = np.argsort(weights, axis=1)
    
    # Initialize all groups and slots as free
    free_groups = set(range(len(groups)))
    matches = [-1] * len(slots)
    group_proposals = [0] * len(groups)
    
    while free_groups:
        g = free_groups.pop()
        s = preferences[g][group_proposals[g]]
        group_proposals[g] += 1
        
        if matches[s] == -1:
            matches[s] = g
        else:
            current_g = matches[s]
            if weights[current_g][s] > weights[g][s]:
                matches[s] = g
                free_groups.add(current_g)
            else:
                free_groups.add(g)
    
    return matches

# Generate multiple variations of weights
weight_variations = generate_random_weights(base_weights, num_variations=5)

# Run the algorithm for unrandomized weights
print("Unrandomized scenario:\n")
print("Weights matrix:")
print(" ", end=" ")  # Changed to match randomized format
for slot in slots:
    print(f"{slot[:2]}{slot[4:6]}", end=" ")  # Changed to match randomized format
print()
print(base_weights.round(2))
final_matches = gale_shapley_matching(base_weights)
print("\nMatching results:")
for slot_idx, group_idx in enumerate(final_matches):
    print(f"{slots[slot_idx]} -> {groups[group_idx]}")
print("\n" + "-"*40 + "\n")

# Run the algorithm for each variation
print("Randomized scenarios:\n")
for i, weights in enumerate(weight_variations, 1):
    print(f"Scenario {i}:")
    print("Weights matrix:")
    print(" ", end=" ")  # Changed to match randomized format
    for slot in slots:
        print(f"{slot[:2]}{slot[4:6]}", end=" ")  # Changed to match randomized format
    print()
    print(weights.round(2))
    final_matches = gale_shapley_matching(weights)
    print("\nMatching results:")
    for slot_idx, group_idx in enumerate(final_matches):
        print(f"{slots[slot_idx]} -> {groups[group_idx]}")
    print("\n" + "-"*40 + "\n")

{'Group1':     Time       Mon       Tue       Wed       Thu       Fri
0  07:00  7.049619  5.128611  1.424239  8.418843  1.164609
1  08:00  6.094127  5.857780  9.623784  4.935872  3.098919
2  09:00  4.776795  0.657197  9.711859  0.282445  2.371565
3  10:00  2.435815  1.807804  9.399971  1.704137  9.196335
4  11:00  5.786670  1.834192  8.976093  2.246180  3.208107
5  12:00  5.334409  6.980180  2.390411  8.640002  1.482983
6  13:00  3.417016  1.512711  6.115688  2.160933  6.111670
7  14:00  2.520701  4.193175  3.905730  5.751717  9.352200
8  15:00  7.737075  5.133789  0.133654  5.540474  0.729326
9  16:00  6.786428  6.731779  2.699872  1.171058  3.125227, 'Group2':     Time       Mon       Tue       Wed       Thu       Fri
0  07:00  0.562177  5.479195  2.727380  5.884677  3.822382
1  08:00  2.852836  8.897264  3.439347  7.492966  9.589122
2  09:00  8.474503  6.765480  6.831249  7.928676  9.187422
3  10:00  3.227517  4.495197  6.136014  5.081786  8.890157
4  11:00  8.621918  4.313460  0.95

In [6]:
sample_data["Group1"]

Time       Mon       Tue       Wed       Thu       Fri
0  07:00  7.049619  5.128611  1.424239  8.418843  1.164609
1  08:00  6.094127  5.857780  9.623784  4.935872  3.098919
2  09:00  4.776795  0.657197  9.711859  0.282445  2.371565
3  10:00  2.435815  1.807804  9.399971  1.704137  9.196335
4  11:00  5.786670  1.834192  8.976093  2.246180  3.208107
5  12:00  5.334409  6.980180  2.390411  8.640002  1.482983
6  13:00  3.417016  1.512711  6.115688  2.160933  6.111670
7  14:00  2.520701  4.193175  3.905730  5.751717  9.352200
8  15:00  7.737075  5.133789  0.133654  5.540474  0.729326
9  16:00  6.786428  6.731779  2.699872  1.171058  3.125227

In [3]:
import numpy as np
import pandas as pd

def read_excel_data(file_path):
    try:
        # Read Excel file with multiple sheets (one per group)
        xl = pd.ExcelFile(file_path)
        group_data_dict = {}
        for sheet_name in xl.sheet_names:
            # Specify the range A1:F11 explicitly
            df = pd.read_excel(xl, 
                             sheet_name=sheet_name, 
                             usecols="A:F",    # Columns A through F
                             nrows=11)         # First 11 rows
            # Ensure the DataFrame has the expected structure
            if 'Time' in df.columns:
                group_data_dict[sheet_name] = df
        return group_data_dict if group_data_dict else None
    except Exception as e:
        print(f"Error reading Excel file: {e}")
        return None

def create_sample_data(num_groups, excel_file=None):
    # Try to read Excel data first
    excel_data = read_excel_data(excel_file) if excel_file else None
    
    group_data_dict = {}
    time_slots = [f"{i:02d}:00" for i in range(7, 17)]
    days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
    
    if excel_data:
        # Process Excel data when available
        for group_name, df in excel_data.items():
            # Ensure the DataFrame has the required columns
            if all(day in df.columns for day in days) and 'Time' in df.columns:
                # Convert time format if needed
                df['Time'] = df['Time'].apply(lambda x: f"{int(x):02d}:00" if isinstance(x, (int, float)) else x)
                group_data_dict[group_name] = df[['Time'] + days]
    else:
        # Fallback to numbered groups if no Excel file
        for i in range(num_groups):
            group_name = f'Group{i+1}'
            data = {'Time': time_slots}
            for day in days:
                data[day] = np.random.rand(len(time_slots)) * 10
            group_data_dict[group_name] = pd.DataFrame(data)
    return group_data_dict

# Use sample data with optional Excel input
excel_path = 'weights.xlsx'  # Update this path as needed
sample_data = create_sample_data(4, excel_file=excel_path)

# Define groups and slots
# groups = [f'Group{i+1}' for i in range(4)]
groups = list(sample_data.keys())
slots = ['Mon_07:00', 'Mon_08:00', 'Tue_07:00', 'Tue_08:00']

def generate_random_weights(base_weights, num_variations=5):
    # Create multiple variations of the weights matrix
    variations = []
    for _ in range(num_variations):
        # Add random noise of order 2 to the base weights
        noise = np.random.uniform(-2, 2, base_weights.shape)
        # Ensure weights remain positive by taking absolute value
        new_weights = np.abs(base_weights + noise)
        variations.append(new_weights)
    return variations

# Base weights matrix
# print(sample_data)
base_weights = np.array([
    [sample_data[g].loc[
        sample_data[g].Time == s.split('_')[1],
        s.split('_')[0]
    ].values[0] for s in slots
    ] for g in groups
])

def gale_shapley_matching(weights):
    # Convert weights to preferences
    preferences = np.argsort(weights, axis=1)
    n_groups, n_slots = weights.shape
    
    # Initialize all groups and slots as free
    free_groups = set(range(n_groups))
    matches = [-1] * n_slots
    group_proposals = [0] * n_groups
    
    while free_groups:
        g = free_groups.pop()
        # Check if group has already proposed to all slots
        if group_proposals[g] >= n_slots:
            continue
        
        s = preferences[g][group_proposals[g]]
        group_proposals[g] += 1
        
        if matches[s] == -1:
            matches[s] = g
        else:
            current_g = matches[s]
            if weights[current_g][s] > weights[g][s]:
                matches[s] = g
                free_groups.add(current_g)
            else:
                free_groups.add(g)
    
    return matches

# Generate multiple variations of weights
weight_variations = generate_random_weights(base_weights, num_variations=5)

# Run the algorithm for unrandomized weights
print("Original scenario:\n")
print("Weights matrix:")
print(" ", end=" ")  # Changed to match randomized format
for slot in slots:
    print(f"{slot[:2]}{slot[4:6]}", end=" ")  # Changed to match randomized format
print()
print(base_weights.round(2))
final_matches = gale_shapley_matching(base_weights)
print("\nMatching results:")
for slot_idx, group_idx in enumerate(final_matches):
    print(f"{slots[slot_idx]} -> {groups[group_idx]}")
print("\n" + "-"*40 + "\n")

# Run the algorithm for each variation
print("Randomized scenarios:\n")
for i, weights in enumerate(weight_variations, 1):
    print(f"Scenario {i}:")
    print("Weights matrix:")
    print(" ", end=" ")  # Changed to match randomized format
    for slot in slots:
        print(f"{slot[:2]}{slot[4:6]}", end=" ")  # Changed to match randomized format
    print()
    print(weights.round(2))
    final_matches = gale_shapley_matching(weights)
    print("\nMatching results:")
    for slot_idx, group_idx in enumerate(final_matches):
        print(f"{slots[slot_idx]} -> {groups[group_idx]}")
    print("\n" + "-"*40 + "\n")

Original scenario:

Weights matrix:
  Mo07 Mo08 Tu07 Tu08 
[[2. 3. 1. 3.]
 [5. 8. 2. 1.]
 [3. 6. 7. 8.]
 [5. 3. 7. 7.]
 [9. 7. 2. 4.]
 [9. 5. 0. 5.]]

Matching results:
Mon_07:00 -> Group 1
Mon_08:00 -> Group 4
Tue_07:00 -> Group 60
Tue_08:00 -> Group 2

----------------------------------------

Randomized scenarios:

Scenario 1:
Weights matrix:
  Mo07 Mo08 Tu07 Tu08 
[[2.67 4.94 2.63 3.13]
 [4.89 6.47 0.94 2.32]
 [3.48 5.26 7.45 7.74]
 [4.7  2.85 8.99 5.36]
 [8.77 5.73 3.79 5.63]
 [8.85 6.39 0.75 6.25]]

Matching results:
Mon_07:00 -> Group 1
Mon_08:00 -> Group 4
Tue_07:00 -> Group 60
Tue_08:00 -> Group 2

----------------------------------------

Scenario 2:
Weights matrix:
  Mo07 Mo08 Tu07 Tu08 
[[ 1.96  4.81  1.35  2.98]
 [ 4.03  6.05  0.36  0.35]
 [ 4.36  7.17  5.81  9.41]
 [ 4.03  4.78  7.23  7.88]
 [10.96  7.68  1.32  3.49]
 [10.15  6.89  0.78  5.46]]

Matching results:
Mon_07:00 -> Group 1
Mon_08:00 -> Group 4
Tue_07:00 -> Group 60
Tue_08:00 -> Group 2

------------------------